DELETE FROM attr_module_data;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_MessageModule', 'Rows', '20') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_MessageModule', 'Moderators', 'root, admin') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_MessageModule', 'Attachment', 'false') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_MessageModule', 'StartAsList', 'true') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_MessageModule', 'ShowSubject', 'false') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_shout.ShoutModule', 'ShoutId', 'portal_shout') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_shout.ShoutModule', 'Moderators', 'root, admin') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_shout.ShoutModule', 'width', '100%') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_shout.ShoutModule', 'height', '200') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_ForumModule', 'Rows', '20') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_ForumModule', 'Moderators', 'root, admin') ;
INSERT INTO attr_module_data (module_id, attribute_name, attribute_value)  VALUES ('lebah_app_ForumModule', 'Attachment', 'false') ;
