create unique index idx_breakdown_marks on breakdown_marks (session_id, subject_id);
create unique index idx_course on course (course_id);
create unique index idx_course_enroll on course_enroll (course_id, member_id);
create unique index idx_course_portfolio_text on course_portfolio_text (subject_id);
create unique index idx_course_sco on course_sco (course_id, sco_id);
create unique index idx_course_structure on course_structure (course_id, period_root_id, period_id, subject_id);
create unique index idx_course_url on course_url (subject_id);
create unique index idx_degree_scheme on degree_scheme (scheme_id);
create unique index idx_degree_scheme_impl on degree_scheme_impl (scheme_id, session_id, program_code);
create unique index idx_enquiry on enquiry (program_code, name);
create unique index idx_faculty on faculty (faculty_id, institution_id);
create unique index idx_faculty_subject on faculty_subject (faculty_id, subject_id);
create unique index idx_fee_code on fee_code (code);
create unique index idx_fee_structure_program on fee_structure_program (fee_id, period_id, fee_code, program_code, intake_session);
create unique index idx_forum on forum (id, parent_id, category_id, member_id);
create unique index idx_forum_attachment on forum_attachment (forum_id);
create unique index idx_gender_code on gender_code (code);
create unique index idx_grading_scheme on grading_scheme (scheme_id);
create unique index idx_grading_scheme_detail on grading_scheme_detail (scheme_id, grade_id);
create unique index idx_grading_scheme_impl on grading_scheme_impl (scheme_id, session_id, program_code);
create unique index idx_hd_categories on hd_categories (category_id);
create unique index idx_hd_escalation on hd_escalation (enquiry_id, responsible_id);
create unique index idx_hd_group on hd_group (group_id);
create unique index idx_hd_responsible_group on hd_responsible_group (group_id, res_id);
create unique index idx_hd_responsibles on hd_responsibles (res_id);
create unique index idx_institution on institution (institution_id);
create unique index idx_intake on intake (intake_id);
create unique index idx_intake_batch on intake_batch (session_id, intake_session, period_root_id, period_id);
create unique index idx_learner_sco on learner_sco (sco_id, member_id);
create unique index idx_learning_centre on learning_centre (centre_id, institution_id);
create unique index idx_lesson on lesson (subject_id, lesson_id);
create unique index idx_lesson_content on lesson_content (lesson_id, content_id);
create unique index idx_letter_compose on letter_compose (letter_id);
create unique index idx_marital_code on marital_code (code);
create unique index idx_marking_part on marking_part (scheme_id, part_id);
create unique index idx_member on member (member_id);
create unique index idx_member_subject on member_subject (member_id, subject_id, module_id);
create unique index idx_module on module (module_id);
create unique index idx_module_htmlcontainer on module_htmlcontainer (module_id);
create unique index idx_nationality_code on nationality_code (code);
create unique index idx_period on period (period_root_id, period_id, parent_id);
create unique index idx_period_root on period_root (period_root_id);
create unique index idx_planner_task on planner_task (task_id, user_login, subject_id);
create unique index idx_planner_task_access on planner_task_access (task_id, user_login);
create unique index idx_planner_task_invite on planner_task_invite (task_id, user_id, inviter_id);
create unique index idx_planner_task_post on planner_task_post (task_id, user_id);
create unique index idx_program on program (course_id, period_root_id, program_code);
create unique index idx_program_intake on program_intake (program_code, intake_session, period_root_id);
create unique index idx_program_track on program_track (program_code, track_id, period_root_id);
create unique index idx_quiz_assessment on quiz_assessment (assessment_id, subject_id);
create unique index idx_quiz_assessment_answer on quiz_assessment_answer (user_id, assessment_id, question_id);
create unique index idx_quiz_assessment_attempt on quiz_assessment_attempt (user_id, assessment_id);
create unique index idx_quiz_assessment_questions on quiz_assessment_questions (assessment_id, quiz_id);
create unique index idx_quiz_assessment_result on quiz_assessment_result (assessment_id, user_id);
create unique index idx_quiz_assessment_run on quiz_assessment_run (user_id, assessment_id, question_id);
create unique index idx_quiz_choice on quiz_choice (choice_id, question_id);
create unique index idx_quiz_main on quiz_main (quiz_id, lesson_id, subject_id);
create unique index idx_quiz_question on quiz_question (question_id, quiz_id);
create unique index idx_race_code on race_code (code);
create unique index idx_religion_code on religion_code (code);
create unique index idx_role_module on role_module (module_id, user_role);
create unique index idx_rss_module on rss_module (module_id);
create unique index idx_sc_category on sc_category (id);
create unique index idx_sc_content on sc_content (user_login, itemId);
create unique index idx_sc_item on sc_item (id, catId);
create unique index idx_sc_item_category on sc_item_category (itemId, catId);
create unique index idx_sco on sco (sco_id);
create unique index idx_sessions on sessions (session_id);
create unique index idx_sponsor on sponsor (sponsor_id);
create unique index idx_state_code on state_code (code);
create unique index idx_student on student (id, name, icno, centre_id);
create unique index idx_student_billing on student_billing (student_id, session_id, bill_no);
create unique index idx_student_billing_detail on student_billing_detail (student_id, bill_no, session_id, period_id, fee_id);
create unique index idx_student_biodata on student_biodata (student_id, icno);
create unique index idx_student_centre on student_centre (student_id, centre_id, session_id);
create unique index idx_student_course on student_course (student_id, course_id, period_root_id, intake_session, program_code);
create unique index idx_student_deposit on student_deposit (student_id, icno, receipt_no, intake_session);
create unique index idx_student_marks on student_marks (student_id, period_id, subject_id, part_id);
create unique index idx_student_marks_total on student_marks_total (student_id, period_id, subject_id);
create unique index idx_student_receipt on student_receipt (student_id, receipt_no);
create unique index idx_student_receipt_detail on student_receipt_detail (student_id, receipt_no, fee_id);
create unique index idx_student_sponsor on student_sponsor (student_id, sponsor_id);
create unique index idx_student_status on student_status (student_id, session_id, batch_id);
create unique index idx_student_subject on student_subject (student_id, period_root_id, period_id, subject_id, course_id, program_code);
create unique index idx_study_course on study_course (course_id, faculty_id);
create unique index idx_subject on subject (subject_id, module_id);
create unique index idx_subject_program on subject_program (subject_id, program_code);
create unique index idx_subject_reg_status on subject_reg_status (status_id);
create unique index idx_tab_template on tab_template (tab_id);
create unique index idx_tabs on tabs (tab_id);
create unique index idx_teacher_comment on teacher_comment (member_id, subject_id);
create unique index idx_transcript_display on transcript_display (student_id);
create unique index idx_tt_prepare_classroom on tt_prepare_classroom (uid, subject_id, section_id, teacher_id, room_id);
create unique index idx_tt_schedule on tt_schedule (uid, subject_id, section_id, teacher_id, room_id, day_id, slot_id);
create unique index idx_tt_section on tt_section (uid, subject_id, section_id, student_id, session_id);
create unique index idx_user_css on user_css (user_login);
create unique index idx_user_module on user_module (tab_id, user_login, module_id);
create unique index idx_user_module_template on user_module_template (tab_id, user_login, module_id);
create unique index idx_user_tracker on user_tracker (user_login, module_id, log_date);
create unique index idx_users on users (user_login);
create unique index idx_xml_module on xml_module (module_id);