DROP TABLE IF EXISTS adm_applicant;
CREATE TABLE adm_applicant ( applicant_id varchar(50),  applicant_name varchar(100),  address1 varchar(100),  address2 varchar(100),  address3 varchar(100),  city varchar(100),  state varchar(100),  poscode varchar(50),  country_code varchar(50),  phone varchar(50),  gender varchar(10),  password varchar(50),  birth_date datetime,  email varchar(50),  vet_rule_scheme_id varchar(50),  vet_program_id varchar(50),  vet_date datetime,  status varchar(50),  applicant_status int,  offer_letter_text varchar(2147483647),  status2 varchar(50),  offer_letter_addr varchar(2147483647),  offer_letter_salutation varchar(2147483647),  offer_letter_subject varchar(2147483647),  offer_letter_signature varchar(2147483647),  apply_date datetime,  ip_address varchar(50),  offered_date datetime,  offer_letter_title varchar(255));
DROP TABLE IF EXISTS adm_applicant_choice;
CREATE TABLE adm_applicant_choice ( applicant_id varchar(50),  choice1 varchar(50),  choice2 varchar(50),  choice3 varchar(50));
DROP TABLE IF EXISTS adm_applicant_exam;
CREATE TABLE adm_applicant_exam ( applicant_id varchar(50),  adm_exam_id varchar(50),  adm_subject_id varchar(50),  adm_subject_grade int);
DROP TABLE IF EXISTS adm_applicant_selected;
CREATE TABLE adm_applicant_selected ( applicant_id varchar(50),  rule_scheme_id varchar(50),  program_id varchar(50),  date_vetted date);
DROP TABLE IF EXISTS adm_display_grade;
CREATE TABLE adm_display_grade ( adm_grade_display_id varchar(50),  adm_grade_value int,  adm_grade_display varchar(50));
DROP TABLE IF EXISTS adm_display_grade_main;
CREATE TABLE adm_display_grade_main ( adm_grade_display_id varchar(50),  adm_grade_display_name varchar(100));
DROP TABLE IF EXISTS adm_exam;
CREATE TABLE adm_exam ( adm_exam_id varchar(50),  adm_exam_name varchar(200),  display varchar(10));
DROP TABLE IF EXISTS adm_exam_subject;
CREATE TABLE adm_exam_subject ( adm_subject_id varchar(50),  adm_exam_id varchar(50),  adm_subject_name varchar(100),  adm_grade_display_id varchar(50));
DROP TABLE IF EXISTS adm_qualifier_factor;
CREATE TABLE adm_qualifier_factor ( qualifier_id varchar(50),  adm_subject_id varchar(50),  qualifier_subject_grade int,  qualifier_operator varchar(10));
DROP TABLE IF EXISTS adm_rule_scheme;
CREATE TABLE adm_rule_scheme ( rule_scheme_id varchar(50),  qualifier_id varchar(50),  rule_sequence int,  condition_operator int,  rule_group int);
DROP TABLE IF EXISTS adm_rule_scheme_main;
CREATE TABLE adm_rule_scheme_main ( rule_scheme_id varchar(50),  rule_scheme_name varchar(200));
DROP TABLE IF EXISTS adm_subject_grade;
CREATE TABLE adm_subject_grade ( adm_subject_id varchar(50),  grade_value int,  grade_display varchar(10));
DROP TABLE IF EXISTS applicant_reminder;
CREATE TABLE applicant_reminder ( reminder_no int,  days_after int);
DROP TABLE IF EXISTS applicant_status;
CREATE TABLE applicant_status ( status_id varchar(50),  status_name varchar(60),  status_description varchar(255));
DROP TABLE IF EXISTS armed_forces_major;
CREATE TABLE armed_forces_major ( major_id varchar(50),  service_id varchar(50),  service_code varchar(50),  major_code varchar(50),  major_name varchar(100));
DROP TABLE IF EXISTS armed_forces_rank;
CREATE TABLE armed_forces_rank ( rank_id varchar(50),  service_id varchar(50),  rank_code varchar(50),  rank_name varchar(100));
DROP TABLE IF EXISTS armed_forces_service;
CREATE TABLE armed_forces_service ( service_id varchar(50),  service_code varchar(50),  service_name varchar(100),  category varchar(100));
DROP TABLE IF EXISTS armed_forces_team;
CREATE TABLE armed_forces_team ( team_id varchar(50),  service_id varchar(50),  major_id varchar(50),  team_code varchar(50),  team_name varchar(100));
DROP TABLE IF EXISTS armed_forces_unit;
CREATE TABLE armed_forces_unit ( unit_id varchar(50),  service_id varchar(50),  unit_code varchar(50),  unit_name varchar(100));
DROP TABLE IF EXISTS article_text;
CREATE TABLE article_text ( subject_id varchar(50),  page_id varchar(50),  page_no int,  content_text varchar(2147483647));
DROP TABLE IF EXISTS attr_module_data;
CREATE TABLE attr_module_data ( module_id varchar(100),  attribute_name varchar(100),  attribute_value varchar(255));
DROP TABLE IF EXISTS billing_doc;
CREATE TABLE billing_doc ( doc_name varchar(50),  doc_prefix varchar(50),  doc_num_size int,  doc_current_num bigint,  last_prefix varchar(40));
DROP TABLE IF EXISTS biodata_kf;
CREATE TABLE biodata_kf ( student_id varchar(50),  code_rank varchar(50),  code_choir varchar(50),  code_regiment varchar(50),  code_unit varchar(50),  code_service varchar(50));
DROP TABLE IF EXISTS breakdown_marks;
CREATE TABLE breakdown_marks ( session_id varchar(50),  subject_id varchar(50),  breakdown_id varchar(50),  breakdown_name varchar(50),  breakdown_value int);
DROP TABLE IF EXISTS calendar_event;
CREATE TABLE calendar_event ( uid varchar(50),  event_date datetime,  event_id varchar(50),  event_text varchar(255),  view_scope varchar(50),  user_id varchar(50));
DROP TABLE IF EXISTS choices;
CREATE TABLE choices ( id bigint,  poll_id varchar(50),  text varchar(255),  value bigint);
DROP TABLE IF EXISTS code_army_rank;
CREATE TABLE code_army_rank ( code varchar(50),  name varchar(100),  category varchar(50),  id varchar(50));
DROP TABLE IF EXISTS code_choir;
CREATE TABLE code_choir ( code varchar(50),  name varchar(100),  category varchar(50),  id varchar(50));
DROP TABLE IF EXISTS code_regiment;
CREATE TABLE code_regiment ( code varchar(50),  name varchar(100),  category varchar(50),  id varchar(50));
DROP TABLE IF EXISTS code_service;
CREATE TABLE code_service ( code varchar(50),  name varchar(100),  category varchar(50),  id varchar(50));
DROP TABLE IF EXISTS code_unit;
CREATE TABLE code_unit ( code varchar(50),  name varchar(100),  category varchar(50),  id varchar(50));
DROP TABLE IF EXISTS country;
CREATE TABLE country ( country_code varchar(50),  country_name varchar(50));
DROP TABLE IF EXISTS course;
CREATE TABLE course ( course_id varchar(50),  title varchar(100));
DROP TABLE IF EXISTS course_enroll;
CREATE TABLE course_enroll ( course_id varchar(50),  member_id varchar(50));
DROP TABLE IF EXISTS course_portfolio_text;
CREATE TABLE course_portfolio_text ( subject_id varchar(50),  page_id varchar(50),  page_no int,  portfolio_text varchar(2147483647));
DROP TABLE IF EXISTS course_sco;
CREATE TABLE course_sco ( course_id varchar(50),  sco_id varchar(50),  level int);
DROP TABLE IF EXISTS course_structure;
CREATE TABLE course_structure ( course_id varchar(50),  period_root_id varchar(50),  period_id varchar(50),  subject_id varchar(50),  subject_option char,  program_code varchar(50),  sequence_no int,  intake_session varchar(50));
DROP TABLE IF EXISTS course_url;
CREATE TABLE course_url ( subject_id varchar(50),  link_id varchar(50),  link_title varchar(255),  link_url varchar(100),  link_type varchar(50));
DROP TABLE IF EXISTS coursework_main;
CREATE TABLE coursework_main ( id varchar(50),  title varchar(100),  description varchar(2147483647),  subject_id varchar(50));
DROP TABLE IF EXISTS custom_data;
CREATE TABLE custom_data ( data_id varchar(50),  data_name varchar(100),  value_type varchar(20));
DROP TABLE IF EXISTS custom_data_values;
CREATE TABLE custom_data_values ( data_id varchar(50),  data_value varchar(100));
DROP TABLE IF EXISTS degree_scheme;
CREATE TABLE degree_scheme ( scheme_id varchar(50),  scheme_name varchar(100));
DROP TABLE IF EXISTS degree_scheme_detail;
CREATE TABLE degree_scheme_detail ( scheme_id varchar(50),  cgpa_low float,  cgpa_high float,  class_id varchar(50),  class_name varchar(100));
DROP TABLE IF EXISTS degree_scheme_impl;
CREATE TABLE degree_scheme_impl ( scheme_id varchar(50),  session_id varchar(50),  program_code varchar(50));
DROP TABLE IF EXISTS enquiry;
CREATE TABLE enquiry ( program_code varchar(50),  name varchar(100),  gender varchar(20),  birth_date datetime,  address1 varchar(255),  address2 varchar(255),  state varchar(50),  country_code varchar(50),  phone_home varchar(50),  phone_mobile varchar(50),  email varchar(100),  academic_qualification varchar(100),  academic_year int,  academic_grade varchar(100),  enquiry_body varchar(2147483647),  enquiry_id varchar(50),  city varchar(50),  poscode varchar(50),  date_post datetime,  status varchar(100),  category_id varchar(50),  date_closed datetime,  comment varchar(2147483647),  reply varchar(2147483647),  date_opened datetime,  comment_by varchar(50));
DROP TABLE IF EXISTS enquiry_status;
CREATE TABLE enquiry_status ( status_id varchar(50),  status_name varchar(50),  status_description varchar(255));
DROP TABLE IF EXISTS exam_centre;
CREATE TABLE exam_centre ( centre_id varchar(50),  centre_name varchar(100),  centre_type varchar(50));
DROP TABLE IF EXISTS exam_centre_register;
CREATE TABLE exam_centre_register ( student_id varchar(50),  centre_id varchar(50));
DROP TABLE IF EXISTS exam_date;
CREATE TABLE exam_date ( subject_id varchar(50),  date_exam datetime);
DROP TABLE IF EXISTS exam_register;
CREATE TABLE exam_register ( student_id varchar(50),  subject_id varchar(50),  invoice_no varchar(50),  type varchar(50),  session_id varchar(50));
DROP TABLE IF EXISTS exam_register_invoice;
CREATE TABLE exam_register_invoice ( student_id varchar(50),  invoice_no varchar(50),  type varchar(50));
DROP TABLE IF EXISTS faculty;
CREATE TABLE faculty ( faculty_id varchar(100),  faculty_code varchar(100),  faculty_name varchar(100),  institution_id varchar(50));
DROP TABLE IF EXISTS faculty_subject;
CREATE TABLE faculty_subject ( faculty_id varchar(50),  subject_id varchar(50),  subject_name varchar(255),  subject_code varchar(50),  remark varchar(255),  synopsis varchar(2147483647),  exclude_gpa int,  credit_hrs float,  subject_name_alt varchar(255));
DROP TABLE IF EXISTS fee_code;
CREATE TABLE fee_code ( code varchar(50),  name varchar(100),  additional int);
DROP TABLE IF EXISTS fee_structure_general;
CREATE TABLE fee_structure_general ( fee_code varchar(50),  fee_description varchar(255));
DROP TABLE IF EXISTS fee_structure_program;
CREATE TABLE fee_structure_program ( program_code varchar(50),  fee_code varchar(50),  fee_description varchar(255),  fee_amount float,  fee_id varchar(50),  period_id varchar(50),  period_scheme varchar(50),  priority int,  intake_session varchar(50),  fee_amount_intl float);
DROP TABLE IF EXISTS fee_structure_subject;
CREATE TABLE fee_structure_subject ( fee_type varchar(50),  subject_id varchar(50),  amount_local float,  amount_international float);
DROP TABLE IF EXISTS forum;
CREATE TABLE forum ( id varchar(50),  parent_id varchar(50),  category_id varchar(50),  member_id varchar(50),  posted_date date,  title varchar(255),  description varchar(255),  content varchar(2147483647),  is_parent int,  is_delete int,  message_text varchar(2147483647),  subject_id varchar(50),  classroom_id varchar(50));
DROP TABLE IF EXISTS forum_attachment;
CREATE TABLE forum_attachment ( forum_id varchar(50),  file_name varchar(255),  directory varchar(255));
DROP TABLE IF EXISTS gender_code;
CREATE TABLE gender_code ( code varchar(10),  gender_name varchar(100));
DROP TABLE IF EXISTS grading_scheme;
CREATE TABLE grading_scheme ( scheme_id varchar(50),  scheme_name varchar(50));
DROP TABLE IF EXISTS grading_scheme_detail;
CREATE TABLE grading_scheme_detail ( scheme_id varchar(50),  high_mark float,  low_mark float,  grade_letter varchar(10),  grade_point float,  grade_id varchar(50),  grade_achievement varchar(100));
DROP TABLE IF EXISTS grading_scheme_impl;
CREATE TABLE grading_scheme_impl ( scheme_id varchar(50),  session_id varchar(50),  program_code varchar(50));
DROP TABLE IF EXISTS guestbook;
CREATE TABLE guestbook ( uid varchar(50),  posted_date datetime,  posted_by varchar(50),  message varchar(2147483647),  module_id varchar(100),  remote_address varchar(50),  email varchar(50),  homepage varchar(100));
DROP TABLE IF EXISTS hd_categories;
CREATE TABLE hd_categories ( category_id varchar(50),  category_name varchar(50),  category_description varchar(100));
DROP TABLE IF EXISTS hd_escalation;
CREATE TABLE hd_escalation ( enquiry_id varchar(50),  responsible_id varchar(50),  date_escalate datetime,  date_read datetime,  date_reply datetime,  reply_text varchar(2147483647));
DROP TABLE IF EXISTS hd_group;
CREATE TABLE hd_group ( group_id varchar(50),  group_name varchar(100));
DROP TABLE IF EXISTS hd_responsible_group;
CREATE TABLE hd_responsible_group ( group_id varchar(50),  res_id varchar(50));
DROP TABLE IF EXISTS hd_responsibles;
CREATE TABLE hd_responsibles ( res_id varchar(50),  res_email varchar(50),  res_phone_office varchar(50),  res_phone_mobile varchar(50),  res_phone_home varchar(50));
DROP TABLE IF EXISTS hrd_company;
CREATE TABLE hrd_company ( company_id varchar(50),  company_name varchar(255),  company_address varchar(255),  as_employer varchar(10),  as_provider varchar(10),  register_date datetime);
DROP TABLE IF EXISTS hrd_course;
CREATE TABLE hrd_course ( course_id varchar(50),  course_code varchar(100),  course_name varchar(255),  course_synopsis varchar(2147483647),  provider_id varchar(50),  status varchar(50));
DROP TABLE IF EXISTS hrd_schedule;
CREATE TABLE hrd_schedule ( schedule_id varchar(50),  course_id varchar(100),  date_start datetime,  date_end datetime);
DROP TABLE IF EXISTS hrd_user;
CREATE TABLE hrd_user ( user_id varchar(50),  company_id varchar(50),  name varchar(255));
DROP TABLE IF EXISTS image_gallery_group;
CREATE TABLE image_gallery_group ( group_id varchar(50),  module_id varchar(50),  title varchar(255),  ord int,  num_of_col int,  items_per_page int);
DROP TABLE IF EXISTS image_gallery_item;
CREATE TABLE image_gallery_item ( item_id varchar(50),  group_id varchar(50),  caption varchar(255),  filename varchar(255),  thumbnail varchar(255),  ord int);
DROP TABLE IF EXISTS image_holder;
CREATE TABLE image_holder ( id int,  module_id varchar(100),  ord int,  image_url varchar(255),  target_url varchar(255),  hits int,  latest_hit date,  is_flash int,  width varchar(5),  height varchar(5),  caption varchar(255),  upload_date date);
DROP TABLE IF EXISTS inceif_app_exemption;
CREATE TABLE inceif_app_exemption ( app_uid varchar(50),  subject_id varchar(50));
DROP TABLE IF EXISTS inceif_applicant;
CREATE TABLE inceif_applicant ( uid varchar(50),  app_name varchar(255),  app_icno varchar(50),  app_birthdate datetime,  app_nationality varchar(50),  app_religion varchar(50),  app_email varchar(50),  app_address varchar(255),  app_city varchar(50),  app_state varchar(50),  app_postcode varchar(50),  app_country varchar(50),  app_telephone varchar(50),  app_mobile varchar(50),  app_facsimile varchar(50),  app_current_level varchar(100),  app_studyfield varchar(100),  app_institute varchar(255),  app_yeargrad int,  app_current_level2 varchar(100),  app_studyfield2 varchar(100),  app_institute2 varchar(255),  app_yeargrad2 int,  app_cgpa float,  app_cgpa2 float,  app_certification_name varchar(255),  app_certification_name2 varchar(255),  app_certification_year int,  app_certification_year2 int,  app_certification_result varchar(100),  app_certification_result2 varchar(100),  app_certification_name3 varchar(100),  app_certification_year3 int,  app_certification_result3 varchar(100),  app_employment_status varchar(50),  app_employment_company varchar(255),  app_employment_position varchar(50),  app_employment_position_other varchar(100),  app_employment_industry varchar(50),  app_employment_industry_other varchar(100),  app_employment_service int,  app_employment_company2 varchar(255),  app_employment_position2 varchar(50),  app_employment_position_other2 varchar(100),  app_employment_industry2 varchar(50),  app_employment_industry_other2 varchar(100),  app_employment_service2 int,  app_funding varchar(50),  app_funding_body varchar(255),  app_ref varchar(50),  app_password varchar(50),  app_disability varchar(255),  app_passport varchar(50),  app_ip_address varchar(50),  app_status varchar(50),  app_date datetime,  app_firstname varchar(100),  app_lastname varchar(100),  mark varchar(50),  app_gender varchar(50),  prereg_date datetime,  app_status_date datetime,  offered_date datetime,  reminder_date datetime,  reminder_age_days varchar(50000));
DROP TABLE IF EXISTS inceif_applicant_fee;
CREATE TABLE inceif_applicant_fee ( uid varchar(50),  fee_code varchar(50),  fee_name varchar(100),  fee_amount float);
DROP TABLE IF EXISTS inceif_counter;
CREATE TABLE inceif_counter ( prefix varchar(50),  num_size int,  current_num int,  suffix varchar(50));
DROP TABLE IF EXISTS inceif_fee_course;
CREATE TABLE inceif_fee_course ( subject_id varchar(50),  fee_code varchar(50),  amount_local float,  amount_international float,  fee_type varchar(50));
DROP TABLE IF EXISTS inceif_fee_general;
CREATE TABLE inceif_fee_general ( fee_id varchar(50),  fee_code varchar(50),  fee_name varchar(255),  amount_local float,  amount_international float);
DROP TABLE IF EXISTS inceif_letter;
CREATE TABLE inceif_letter ( app_address varchar(255),  app_salutation varchar(255),  app_subject varchar(255),  app_content varchar(2147483647),  app_signature varchar(255),  app_status varchar(50),  app_title varchar(255));
DROP TABLE IF EXISTS institution;
CREATE TABLE institution ( institution_id varchar(50),  institution_name varchar(100),  institution_abbr varchar(50));
DROP TABLE IF EXISTS intake;
CREATE TABLE intake ( intake_id varchar(50),  intake_name varchar(50),  intake_begin date);
DROP TABLE IF EXISTS intake_batch;
CREATE TABLE intake_batch ( session_id varchar(50),  intake_session varchar(50),  period_root_id varchar(50),  period_id varchar(50));
DROP TABLE IF EXISTS ip2country;
CREATE TABLE ip2country ( ip_from double,  ip_to double,  registry varchar(60),  assigned varchar(60),  country_code char,  country_code2 varchar(4),  country_name varchar(100));
DROP TABLE IF EXISTS items;
CREATE TABLE items ( item_name varchar(50),  item_price float,  id varchar(50));
DROP TABLE IF EXISTS kix_organizer;
CREATE TABLE kix_organizer ( id int,  module_id varchar(100),  owner varchar(100),  task_date date,  time_begin time,  time_end time,  task varchar(2147483647),  priority int,  post_date timestamp);
DROP TABLE IF EXISTS kix_organizer_group;
CREATE TABLE kix_organizer_group ( id int,  module_id varchar(100),  name_list varchar(255));
DROP TABLE IF EXISTS learner_sco;
CREATE TABLE learner_sco ( cmi_name varchar(50),  cmi_value varchar(50),  course_id varchar(50),  sco_id varchar(255),  member_id varchar(50),  cmi_value_text varchar(2147483647));
DROP TABLE IF EXISTS learning_centre;
CREATE TABLE learning_centre ( centre_id varchar(50),  institution_id varchar(50),  centre_name varchar(50),  centre_address varchar(255),  centre_code varchar(50));
DROP TABLE IF EXISTS lesson;
CREATE TABLE lesson ( subject_id varchar(50),  lesson_id varchar(50),  lesson_title varchar(100),  lesson_sequence int,  lesson_description varchar(2147483647));
DROP TABLE IF EXISTS lesson_content;
CREATE TABLE lesson_content ( lesson_id varchar(50),  content_type varchar(50),  content_id varchar(255),  content_title varchar(255),  content_url varchar(255),  sequence_no int);
DROP TABLE IF EXISTS letter_compose;
CREATE TABLE letter_compose ( letter_id varchar(50),  content varchar(2147483647),  applicant_address varchar(2147483647),  salutation varchar(2147483647),  subject varchar(2147483647),  signature varchar(2147483647));
DROP TABLE IF EXISTS lib_book;
CREATE TABLE lib_book ( book_id varchar(50),  title varchar(255),  author varchar(255),  synopsis varchar(2147483647));
DROP TABLE IF EXISTS lib_book_copy;
CREATE TABLE lib_book_copy ( copy_id varchar(50),  item_id varchar(50),  book_id varchar(50),  code varchar(50),  when_available varchar(50),  onloan varchar(50),  loanby_id varchar(50));
DROP TABLE IF EXISTS lib_book_item;
CREATE TABLE lib_book_item ( item_id varchar(50),  book_id varchar(50),  isbn varchar(50),  cover varchar(50),  language varchar(50),  loanable varchar(50));
DROP TABLE IF EXISTS library_category;
CREATE TABLE library_category ( category_id varchar(50),  category_name varchar(50),  category_type varchar(50));
DROP TABLE IF EXISTS library_group;
CREATE TABLE library_group ( group_id varchar(50),  group_name varchar(50),  category_id varchar(50));
DROP TABLE IF EXISTS library_item;
CREATE TABLE library_item ( item_id varchar(50),  item_name varchar(50),  file_name varchar(100),  group_id varchar(50),  item_description varchar(255),  file_thumbname varchar(255),  thumb_filename varchar(255),  user_id varchar(50),  date_upload datetime,  item_title varchar(100),  faculty_code varchar(50),  file_type varchar(50),  url_path varchar(255));
DROP TABLE IF EXISTS lms_attendance;
CREATE TABLE lms_attendance ( user_id varchar(50),  classroom_id varchar(50),  log_date datetime,  log_date2 datetime,  date_str varchar(50),  remote_addr varchar(50),  counter int);
DROP TABLE IF EXISTS log_country;
CREATE TABLE log_country ( country_name varchar(100),  counts bigint);
DROP TABLE IF EXISTS marital_code;
CREATE TABLE marital_code ( code varchar(10),  status_name varchar(100));
DROP TABLE IF EXISTS marking_part;
CREATE TABLE marking_part ( scheme_id varchar(50),  part_id varchar(50),  part_name varchar(50),  part_sequence int,  part_percentage int);
DROP TABLE IF EXISTS marking_scheme;
CREATE TABLE marking_scheme ( scheme_id varchar(50),  scheme_name varchar(50),  mark_type varchar(50));
DROP TABLE IF EXISTS marking_scheme_impl;
CREATE TABLE marking_scheme_impl ( scheme_id varchar(50),  subject_id varchar(50),  session_id varchar(50));
DROP TABLE IF EXISTS matric_generate;
CREATE TABLE matric_generate ( matric_prefix varchar(50),  matric_size int,  matric_currentnum bigint);
DROP TABLE IF EXISTS member;
CREATE TABLE member ( member_id varchar(50),  login varchar(50),  password varchar(50),  name varchar(100));
DROP TABLE IF EXISTS member_subject;
CREATE TABLE member_subject ( member_id varchar(50),  subject_id varchar(50),  role varchar(50),  status varchar(50),  date_apply date,  date_enroll date,  module_id varchar(50),  expiry_date datetime);
DROP TABLE IF EXISTS message;
CREATE TABLE message ( id bigint,  created datetime,  message varchar(255));
DROP TABLE IF EXISTS mobile_module;
CREATE TABLE mobile_module ( role_id varchar(50),  module_id varchar(50),  module_title varchar(255));
DROP TABLE IF EXISTS mobile_sessions;
CREATE TABLE mobile_sessions ( user_id varchar(50),  session_id varchar(50),  current_module varchar(100));
DROP TABLE IF EXISTS module;
CREATE TABLE module ( module_id varchar(100),  module_title varchar(100),  module_class varchar(100),  module_group varchar(100),  module_description varchar(200));
DROP TABLE IF EXISTS module_htmlcontainer;
CREATE TABLE module_htmlcontainer ( module_id varchar(100),  html_url varchar(100));
DROP TABLE IF EXISTS nationality_code;
CREATE TABLE nationality_code ( code varchar(50),  nationality_name varchar(100));
DROP TABLE IF EXISTS page_css;
CREATE TABLE page_css ( css_title varchar(100),  css_name varchar(100));
DROP TABLE IF EXISTS period;
CREATE TABLE period ( period_root_id varchar(50),  period_id varchar(50),  parent_id varchar(50),  period_level int,  period_sequence int,  period_name varchar(100),  display_name varchar(100));
DROP TABLE IF EXISTS period_root;
CREATE TABLE period_root ( period_schema_code varchar(50),  period_root_id varchar(50),  path_no int);
DROP TABLE IF EXISTS person;
CREATE TABLE person ( id varchar(50),  name varchar(100),  icno varchar(50));
DROP TABLE IF EXISTS pfinvoice;
CREATE TABLE pfinvoice ( applicant_id varchar(50),  invoice_no varchar(50),  invoice_date datetime,  amount_total float,  currency varchar(50));
DROP TABLE IF EXISTS pfinvoice_detail;
CREATE TABLE pfinvoice_detail ( applicant_id varchar(50),  invoice_no varchar(50),  fee_id varchar(50),  fee_code varchar(50),  fee_description varchar(255),  amount float,  fee_category varchar(50));
DROP TABLE IF EXISTS planner_task;
CREATE TABLE planner_task ( task_id varchar(100),  user_login varchar(100),  task_description varchar(255),  task_start_date timestamp,  task_end_date timestamp,  task_public int,  subject_id varchar(50),  task_date date,  hour_start int,  hour_end int,  minute_start int,  minute_end int);
DROP TABLE IF EXISTS planner_task_access;
CREATE TABLE planner_task_access ( task_id varchar(50),  user_login varchar(50));
DROP TABLE IF EXISTS planner_task_invite;
CREATE TABLE planner_task_invite ( task_id varchar(100),  user_id varchar(100),  inviter_id varchar(100),  allow_edit int);
DROP TABLE IF EXISTS planner_task_post;
CREATE TABLE planner_task_post ( task_id varchar(100),  user_id varchar(100),  is_editable int);
DROP TABLE IF EXISTS poll;
CREATE TABLE poll ( tbl_id bigint,  id varchar(50),  question varchar(255),  title varchar(255),  txt varchar(2147483647),  start_date date,  expire_date date,  show_result int,  show_poll int);
DROP TABLE IF EXISTS poll_option;
CREATE TABLE poll_option ( id int,  poll_id int,  txt varchar(2147483647),  votes int);
DROP TABLE IF EXISTS poll_tracker;
CREATE TABLE poll_tracker ( poll_id int,  user_id varchar(100));
DROP TABLE IF EXISTS program;
CREATE TABLE program ( course_id varchar(50),  period_root_id varchar(50),  program_name varchar(100),  program_code varchar(50),  program_abbr varchar(50),  program_name_alt varchar(100),  learning_base varchar(50),  program_regno varchar(50),  jps_refno varchar(50),  jps_code varchar(50));
DROP TABLE IF EXISTS program_intake;
CREATE TABLE program_intake ( program_code varchar(50),  intake_session varchar(50),  period_root_id varchar(50));
DROP TABLE IF EXISTS program_track;
CREATE TABLE program_track ( program_code varchar(50),  track_id varchar(50),  track_name varchar(100),  period_root_id varchar(50),  remark varchar(255));
DROP TABLE IF EXISTS project_timeline;
CREATE TABLE project_timeline ( project_id varchar(50),  task_id varchar(50),  task_name varchar(255),  task_start datetime,  task_end datetime,  task_color varchar(50),  percent_completion int);
DROP TABLE IF EXISTS project_timeline_task;
CREATE TABLE project_timeline_task ( task_id varchar(50),  assignee_id varchar(50),  assignee_remark varchar(2147483647),  assigner_remark varchar(2147483647));
DROP TABLE IF EXISTS quiz_assessment;
CREATE TABLE quiz_assessment ( assessment_id varchar(50),  assessment_title varchar(255),  subject_id varchar(50),  created_date datetime,  created_by varchar(50),  start_date datetime,  end_date datetime,  time_limit_hr int,  time_limit_min int,  max_attempt int,  passing_marks int,  accessible_type varchar(50));
DROP TABLE IF EXISTS quiz_assessment_allow;
CREATE TABLE quiz_assessment_allow ( assessment_id varchar(50),  student_id varchar(50));
DROP TABLE IF EXISTS quiz_assessment_answer;
CREATE TABLE quiz_assessment_answer ( user_id varchar(50),  assessment_id varchar(50),  question_id varchar(50),  attempt_no int,  choice_no int,  answer varchar(100));
DROP TABLE IF EXISTS quiz_assessment_attempt;
CREATE TABLE quiz_assessment_attempt ( user_id varchar(50),  assessment_id varchar(50),  attempt_count varchar(50));
DROP TABLE IF EXISTS quiz_assessment_questions;
CREATE TABLE quiz_assessment_questions ( assessment_id varchar(50),  quiz_id varchar(50),  number_of_questions int);
DROP TABLE IF EXISTS quiz_assessment_result;
CREATE TABLE quiz_assessment_result ( assessment_id varchar(50),  user_id varchar(50),  attempt_no varchar(50),  is_passed int,  attempt_date datetime,  time_taken_hr int,  time_taken_min int,  time_taken_sec int,  passing_marks float,  user_marks float,  time_limit_hr int,  time_limit_min int,  date2 datetime);
DROP TABLE IF EXISTS quiz_assessment_run;
CREATE TABLE quiz_assessment_run ( user_id varchar(50),  assessment_id varchar(50),  question_id varchar(50),  question_no int,  attempt_no int);
DROP TABLE IF EXISTS quiz_choice;
CREATE TABLE quiz_choice ( choice_id varchar(50),  question_id varchar(50),  choice_text varchar(255),  is_correct int,  choice_no int);
DROP TABLE IF EXISTS quiz_main;
CREATE TABLE quiz_main ( quiz_id varchar(50),  quiz_title varchar(255),  date_create datetime,  lesson_id varchar(50),  subject_id varchar(50));
DROP TABLE IF EXISTS quiz_question;
CREATE TABLE quiz_question ( question_id varchar(50),  quiz_id varchar(50),  question_text varchar(2147483647),  question_type int,  question_no int);
DROP TABLE IF EXISTS quiz_transcript;
CREATE TABLE quiz_transcript ( user_id varchar(50),  assessment_id varchar(50),  transcript_data varchar(2147483647),  attempt_no int);
DROP TABLE IF EXISTS race_code;
CREATE TABLE race_code ( code varchar(10),  race_name varchar(100));
DROP TABLE IF EXISTS rank_code;
CREATE TABLE rank_code ( code varchar(50),  name varchar(100));
DROP TABLE IF EXISTS register_confirm;
CREATE TABLE register_confirm ( student_id varchar(50),  examination varchar(50),  tutorial varchar(50),  special_session varchar(50));
DROP TABLE IF EXISTS religion_code;
CREATE TABLE religion_code ( code varchar(10),  religion_name varchar(100));
DROP TABLE IF EXISTS role;
CREATE TABLE role ( name varchar(100),  description varchar(255));
DROP TABLE IF EXISTS role_module;
CREATE TABLE role_module ( module_id varchar(100),  user_role varchar(100));
DROP TABLE IF EXISTS rss_module;
CREATE TABLE rss_module ( module_id varchar(100),  rss_source varchar(200));
DROP TABLE IF EXISTS sc_category;
CREATE TABLE sc_category ( id bigint,  root bigint,  parent bigint,  name varchar(255),  description varchar(2147483647),  is_parent int,  is_visible int);
DROP TABLE IF EXISTS sc_content;
CREATE TABLE sc_content ( user_login varchar(20),  itemId bigint);
DROP TABLE IF EXISTS sc_item;
CREATE TABLE sc_item ( id bigint,  catId bigint,  name varchar(255),  description varchar(2147483647),  price varchar(10),  image varchar(255),  post_date date);
DROP TABLE IF EXISTS sc_item_category;
CREATE TABLE sc_item_category ( itemId bigint,  catId bigint);
DROP TABLE IF EXISTS sco;
CREATE TABLE sco ( sco_id varchar(50),  title varchar(100),  languange varchar(20),  description varchar(255),  keywords varchar(255),  lifecycle_version varchar(50),  lifecycle_status varchar(50),  metadata_scheme varchar(50),  edu_resource_type varchar(50),  edu_learning_time varchar(50),  class_purpose varchar(50),  class_keywords varchar(255));
DROP TABLE IF EXISTS session;
CREATE TABLE session ( session_id varchar(50),  session_name varchar(50),  start_date date,  end_date date,  session_name_alt varchar(50),  path_no int,  session_code varchar(50));
DROP TABLE IF EXISTS sessions;
CREATE TABLE sessions ( session_id varchar(50),  session_name varchar(50),  start_date date,  end_date date,  session_name_alt varchar(50),  path_no int,  session_code varchar(50),  start_date_day int,  start_date_month int,  start_date_year int,  end_date_day int,  end_date_month int,  end_date_year int,  exam_session_name varchar(50));
DROP TABLE IF EXISTS shout_box;
CREATE TABLE shout_box ( uid varchar(50),  user_id varchar(50),  category_id varchar(100),  shout_text varchar(2147483647),  shout_date datetime,  user_name varchar(100),  remote_addr varchar(50));
DROP TABLE IF EXISTS sis_log;
CREATE TABLE sis_log ( log_date datetime,  ip_address varchar(50),  username varchar(50),  description varchar(255));
DROP TABLE IF EXISTS sponsor;
CREATE TABLE sponsor ( sponsor_id varchar(50),  sponsor_name varchar(100),  sponsor_address varchar(255));
DROP TABLE IF EXISTS state_code;
CREATE TABLE state_code ( code varchar(50),  state_name varchar(100));
DROP TABLE IF EXISTS stmt_acct_prop;
CREATE TABLE stmt_acct_prop ( uid varchar(50),  program_code varchar(50),  top_note varchar(255),  remark varchar(2147483647));
DROP TABLE IF EXISTS student;
CREATE TABLE student ( id varchar(60),  password varchar(50),  name varchar(100),  address1 varchar(255),  address2 varchar(100),  address3 varchar(100),  city varchar(50),  state varchar(50),  poscode varchar(50),  country_code varchar(50),  phone varchar(50),  gender varchar(10),  birth_date datetime,  email varchar(50),  applicant_id varchar(50),  intake_session varchar(50),  intake_session2 varchar(50),  address varchar(255),  icno varchar(50),  centre_id varchar(50),  guardian_name varchar(100),  guardian_address1 varchar(100),  guardian_address2 varchar(100),  guardian_phone varchar(50),  tempid varchar(50),  tempid2 varchar(50),  status varchar(50),  currency_type varchar(50),  nationality varchar(50),  photoFileName varchar(100));
DROP TABLE IF EXISTS student_billing;
CREATE TABLE student_billing ( student_id varchar(50),  bill_no varchar(50),  bill_date datetime,  amount_total float,  session_id varchar(50),  additional int);
DROP TABLE IF EXISTS student_billing_detail;
CREATE TABLE student_billing_detail ( student_id varchar(50),  bill_no varchar(50),  amount float,  fee_id varchar(50),  session_id varchar(50),  period_id varchar(50),  fee_code varchar(50),  fee_category varchar(50),  fee_description varchar(255));
DROP TABLE IF EXISTS student_biodata;
CREATE TABLE student_biodata ( student_id varchar(50),  phone_no_permanent varchar(50),  phone_no varchar(50),  phone_mobile varchar(50),  gender varchar(50),  disability varchar(50),  marriage_status varchar(50),  religion varchar(50),  race varchar(50),  nationality varchar(50),  guardian_name varchar(200),  date_of_birth varchar(50),  birth_date datetime,  icno varchar(50),  guardian_address1 varchar(100),  guardian_address2 varchar(100),  code_rank varchar(50),  code_choir varchar(50),  code_regiment varchar(50),  code_unit varchar(50),  code_service varchar(50));
DROP TABLE IF EXISTS student_centre;
CREATE TABLE student_centre ( student_id varchar(50),  centre_id varchar(50),  session_id varchar(50));
DROP TABLE IF EXISTS student_course;
CREATE TABLE student_course ( student_id varchar(60),  course_id varchar(50),  period_root_id varchar(50),  intake_session varchar(50),  program_code varchar(50),  track_id varchar(50),  intake_code varchar(10),  intake_year int,  intake_month int,  period_id varchar(50),  date_register datetime);
DROP TABLE IF EXISTS student_custom_data;
CREATE TABLE student_custom_data ( student_id varchar(50),  data_id varchar(50),  data_value varchar(100));
DROP TABLE IF EXISTS student_deposit;
CREATE TABLE student_deposit ( student_id varchar(50),  amount_paid float,  date_paid datetime,  icno varchar(50),  program_code varchar(50),  receipt_no varchar(50),  intake_session varchar(50),  remark varchar(2147483647),  intake_month int,  intake_year int);
DROP TABLE IF EXISTS student_marks;
CREATE TABLE student_marks ( student_id varchar(50),  period_id varchar(50),  subject_id varchar(50),  part_id varchar(50),  mark_value float,  mark_type varchar(50));
DROP TABLE IF EXISTS student_marks_total;
CREATE TABLE student_marks_total ( student_id varchar(50),  period_id varchar(50),  subject_id varchar(50),  mark_total float,  mark_grade varchar(10),  mark_point float);
DROP TABLE IF EXISTS student_payment;
CREATE TABLE student_payment ( invoice_no varchar(50),  payment_date datetime,  student_id varchar(50),  amount_invoice float,  amount_paid float,  amount_unpaid float);
DROP TABLE IF EXISTS student_receipt;
CREATE TABLE student_receipt ( student_id varchar(50),  receipt_no varchar(50),  receipt_date datetime,  amount_total float,  payment_method varchar(50),  serial_no varchar(50),  payment_mode varchar(50),  payment_no varchar(50),  payment_remark varchar(255));
DROP TABLE IF EXISTS student_receipt_detail;
CREATE TABLE student_receipt_detail ( student_id varchar(50),  receipt_no varchar(50),  fee_id varchar(50),  amount varchar(50),  fee_code varchar(50),  fee_description varchar(255));
DROP TABLE IF EXISTS student_sponsor;
CREATE TABLE student_sponsor ( student_id varchar(50),  sponsor_id varchar(50));
DROP TABLE IF EXISTS student_status;
CREATE TABLE student_status ( student_id varchar(50),  session_id varchar(50),  batch_id varchar(50),  repeat_no int,  status varchar(50));
DROP TABLE IF EXISTS student_status2;
CREATE TABLE student_status2 ( student_id varchar(50),  period_id varchar(50),  date_status datetime);
DROP TABLE IF EXISTS student_subject;
CREATE TABLE student_subject ( student_id varchar(60),  period_root_id varchar(50),  period_id varchar(50),  subject_id varchar(50),  course_id varchar(50),  program_code varchar(50),  register_id varchar(50));
DROP TABLE IF EXISTS study_course;
CREATE TABLE study_course ( course_id varchar(50),  course_code varchar(50),  course_name varchar(200),  faculty_id varchar(50));
DROP TABLE IF EXISTS study_status;
CREATE TABLE study_status ( status_id varchar(50),  status_name varchar(100));
DROP TABLE IF EXISTS subject;
CREATE TABLE subject ( subject_id varchar(50),  subject_code varchar(50),  subject_title varchar(100),  subject_comment varchar(255),  subject_text varchar(2147483647),  module_id varchar(50),  classroom_id varchar(50));
DROP TABLE IF EXISTS subject_program;
CREATE TABLE subject_program ( subject_id varchar(50),  program_code varchar(50));
DROP TABLE IF EXISTS subject_reg_status;
CREATE TABLE subject_reg_status ( status_id varchar(50),  status_name varchar(50),  status_category int,  status_description varchar(255),  status_sequence int);
DROP TABLE IF EXISTS subject_temp;
CREATE TABLE subject_temp ( subject_id varchar(50),  subject_code varchar(50),  subject_title varchar(100),  subject_comment varchar(255),  subject_text varchar(2147483647),  module_id varchar(50),  classroom_id varchar(50));
DROP TABLE IF EXISTS tab;
CREATE TABLE tab ( tab_id varchar(100),  tab_title varchar(100),  user_login varchar(100),  sequence int,  display_type varchar(100));
DROP TABLE IF EXISTS tab_template;
CREATE TABLE tab_template ( tab_id varchar(100),  tab_title varchar(100),  user_login varchar(100),  sequence int,  display_type varchar(100),  locked int);
DROP TABLE IF EXISTS tab_user;
CREATE TABLE tab_user ( tab_id varchar(50),  tab_title varchar(50),  user_login varchar(50),  sequence int,  display_type varchar(50),  locked int,  hide int);
DROP TABLE IF EXISTS tabs;
CREATE TABLE tabs ( tab_id varchar(100),  tab_title varchar(100),  user_login varchar(100),  sequence int,  display_type varchar(100));
DROP TABLE IF EXISTS teacher_comment;
CREATE TABLE teacher_comment ( member_id varchar(50),  subject_id varchar(50),  comment varchar(2147483647));
DROP TABLE IF EXISTS temp_current_session;
CREATE TABLE temp_current_session ( session_id varchar(50));
DROP TABLE IF EXISTS test;
CREATE TABLE test ( id varchar(50),  name varchar(50),  address varchar(100));
DROP TABLE IF EXISTS transcript_display;
CREATE TABLE transcript_display ( student_id varchar(50),  period_name varchar(100),  startDate datetime,  session_name varchar(50),  subject_code varchar(50),  subject_name varchar(100),  credit_hrs int,  total float,  point float,  grade_point float,  tot_credit_hrs int,  tot_grade_point float,  gpa varchar(50),  cum_credit_hrs int,  cum_grade_point float,  cgpa varchar(50),  program_code varchar(50),  grade varchar(50),  calculated_credit_hrs int,  period_id varchar(50));
DROP TABLE IF EXISTS tt_prepare_classroom;
CREATE TABLE tt_prepare_classroom ( uid varchar(50),  subject_id varchar(50),  section_id varchar(50),  teacher_id varchar(50),  room_id varchar(50),  user_session varchar(50),  slot_constraint varchar(50),  day_constraint varchar(50));
DROP TABLE IF EXISTS tt_room_impl;
CREATE TABLE tt_room_impl ( room_id varchar(50),  room_code varchar(50),  room_name varchar(50));
DROP TABLE IF EXISTS tt_schedule;
CREATE TABLE tt_schedule ( subject_id varchar(50),  section_id varchar(50),  teacher_id varchar(50),  room_id varchar(50),  day_id int,  slot_id int,  uid varchar(50),  user_session varchar(50));
DROP TABLE IF EXISTS tt_section;
CREATE TABLE tt_section ( subject_id varchar(50),  section_id varchar(50),  student_id varchar(50),  session_id varchar(50),  uid varchar(50));
DROP TABLE IF EXISTS tt_section_impl;
CREATE TABLE tt_section_impl ( section_id varchar(50),  section_code varchar(50),  section_name varchar(255));
DROP TABLE IF EXISTS tt_slot_remark;
CREATE TABLE tt_slot_remark ( slot_id int,  remark varchar(100));
DROP TABLE IF EXISTS tt_slot_span;
CREATE TABLE tt_slot_span ( uid varchar(50),  slot_count int);
DROP TABLE IF EXISTS tt_teacher_impl;
CREATE TABLE tt_teacher_impl ( teacher_id varchar(50),  teacher_code varchar(50),  teacher_name varchar(100));
DROP TABLE IF EXISTS user_css;
CREATE TABLE user_css ( user_login varchar(100),  css_name varchar(100));
DROP TABLE IF EXISTS user_module;
CREATE TABLE user_module ( tab_id varchar(100),  user_login varchar(100),  module_id varchar(100),  sequence int,  module_custom_title varchar(100),  column_number int);
DROP TABLE IF EXISTS user_module_template;
CREATE TABLE user_module_template ( tab_id varchar(100),  user_login varchar(100),  module_id varchar(100),  sequence int,  module_custom_title varchar(100),  column_number int);
DROP TABLE IF EXISTS user_timezone;
CREATE TABLE user_timezone ( user_id varchar(50),  time_zone_id varchar(100));
DROP TABLE IF EXISTS user_tracker;
CREATE TABLE user_tracker ( user_login varchar(50),  log_year int,  log_month int,  log_day int,  module_id varchar(50),  module_class varchar(100),  module_name varchar(100),  time12 varchar(50),  time24 varchar(50),  str_date varchar(50),  remote_add varchar(50),  log_date datetime);
DROP TABLE IF EXISTS users;
CREATE TABLE users ( user_login varchar(100),  user_password varchar(100),  user_name varchar(200),  user_role varchar(100),  user_login_alt varchar(50),  user_address varchar(255),  user_ip_address varchar(50),  date_registered datetime,  avatar varchar(50));
DROP TABLE IF EXISTS users_data;
CREATE TABLE users_data ( user_login varchar(100),  address varchar(255),  state varchar(50),  postcode varchar(10),  emp_address varchar(255),  emp_state varchar(50),  emp_postcode varchar(10),  email varchar(255),  hpno varchar(15),  telno varchar(15),  faxno varchar(15),  icno varchar(16),  age char,  gender char,  marital_status varchar(12),  date_of_birth date,  interest varchar(2147483647),  academic varchar(255),  sector varchar(255),  current_job varchar(255));
DROP TABLE IF EXISTS web_log;
CREATE TABLE web_log ( ip_address varchar(50),  counter bigint,  last_log_date datetime,  first_log_date datetime);
DROP TABLE IF EXISTS web_log_init;
CREATE TABLE web_log_init ( init_date datetime);
DROP TABLE IF EXISTS web_logger;
CREATE TABLE web_logger ( remote_add varchar(50),  user_name varchar(50),  log_year int,  log_month int,  log_day int,  log_string varchar(255),  log_date datetime);
DROP TABLE IF EXISTS webmail_login;
CREATE TABLE webmail_login ( username varchar(50),  password varchar(100),  user_id varchar(50));
DROP TABLE IF EXISTS xml_module;
CREATE TABLE xml_module ( module_id varchar(100),  xml varchar(200),  xsl varchar(200));


