DROP TABLE IF EXISTS calendar_event;
CREATE TABLE calendar_event ( uid varchar(50),  event_date datetime,  event_id varchar(50),  event_text varchar(255),  view_scope varchar(50),  user_id varchar(50));
DROP TABLE IF EXISTS course;
CREATE TABLE course ( course_id varchar(50),  title varchar(100));
DROP TABLE IF EXISTS course_enroll;
CREATE TABLE course_enroll ( course_id varchar(50),  member_id varchar(50));
DROP TABLE IF EXISTS course_portfolio_text;
CREATE TABLE course_portfolio_text ( subject_id varchar(50),  page_id varchar(50),  page_no int,  portfolio_text text);
DROP TABLE IF EXISTS course_sco;
CREATE TABLE course_sco ( course_id varchar(50),  sco_id varchar(50),  level int);
DROP TABLE IF EXISTS course_structure;
CREATE TABLE course_structure ( course_id varchar(50),  period_root_id varchar(50),  period_id varchar(50),  subject_id varchar(50),  subject_option char,  program_code varchar(50),  sequence_no int,  intake_session varchar(50));
DROP TABLE IF EXISTS course_url;
CREATE TABLE course_url ( subject_id varchar(50),  link_id varchar(50),  link_title varchar(255),  link_url varchar(100),  link_type varchar(50));
DROP TABLE IF EXISTS coursework_main;
CREATE TABLE coursework_main ( id varchar(50),  title varchar(100),  description text,  subject_id varchar(50));
DROP TABLE IF EXISTS forum;
CREATE TABLE forum ( id varchar(50),  parent_id varchar(50),  category_id varchar(50),  member_id varchar(50),  posted_date date,  title varchar(255),  description varchar(255),  content text,  is_parent int,  is_delete int,  message_text text,  subject_id varchar(50),  classroom_id varchar(50));
DROP TABLE IF EXISTS forum_attachment;
CREATE TABLE forum_attachment ( forum_id varchar(50),  file_name varchar(255),  directory varchar(255));
DROP TABLE IF EXISTS guestbook;
CREATE TABLE guestbook ( uid varchar(50),  posted_date datetime,  posted_by varchar(50),  message text,  module_id varchar(100),  remote_address varchar(50),  email varchar(50),  homepage varchar(100));
DROP TABLE IF EXISTS ip2country;
CREATE TABLE ip2country ( ip_from double,  ip_to double,  registry varchar(60),  assigned varchar(60),  country_code char,  country_code2 varchar(4),  country_name varchar(100));
DROP TABLE IF EXISTS lms_attendance;
CREATE TABLE lms_attendance ( user_id varchar(50),  classroom_id varchar(50),  log_date datetime,  log_date2 datetime,  date_str varchar(50),  remote_addr varchar(50),  counter int);
DROP TABLE IF EXISTS log_country;
CREATE TABLE log_country ( country_name varchar(100),  count bigint);
DROP TABLE IF EXISTS member;
CREATE TABLE member ( member_id varchar(50),  login varchar(50),  password varchar(50),  name varchar(100));
DROP TABLE IF EXISTS member_subject;
CREATE TABLE member_subject ( member_id varchar(50),  subject_id varchar(50),  role varchar(50),  status varchar(50),  date_apply date,  date_enroll date,  module_id varchar(50),  expiry_date datetime);
DROP TABLE IF EXISTS message;
CREATE TABLE message ( id bigint,  created datetime,  message varchar(255));
DROP TABLE IF EXISTS mobile_sessions;
CREATE TABLE mobile_sessions ( user_id varchar(50),  session_id varchar(50),  current_module varchar(100));
DROP TABLE IF EXISTS module;
CREATE TABLE module ( module_id varchar(100),  module_title varchar(100),  module_class varchar(100),  module_group varchar(100),  module_description varchar(200));
DROP TABLE IF EXISTS module_htmlcontainer;
CREATE TABLE module_htmlcontainer ( module_id varchar(100),  html_url varchar(100));
DROP TABLE IF EXISTS nationality_code;
CREATE TABLE nationality_code ( code varchar(50),  nationality_name varchar(100));
DROP TABLE IF EXISTS page_css;
CREATE TABLE page_css ( css_title varchar(100),  css_name varchar(100));
DROP TABLE IF EXISTS role;
CREATE TABLE role ( name varchar(100),  description varchar(255));
DROP TABLE IF EXISTS role_module;
CREATE TABLE role_module ( module_id varchar(100),  user_role varchar(100));
DROP TABLE IF EXISTS tab;
CREATE TABLE tab ( tab_id varchar(100),  tab_title varchar(100),  user_login varchar(100),  sequence int,  display_type varchar(100));
DROP TABLE IF EXISTS tab_template;
CREATE TABLE tab_template ( tab_id varchar(100),  tab_title varchar(100),  user_login varchar(100),  sequence int,  display_type varchar(100),  locked int);
DROP TABLE IF EXISTS tab_user;
CREATE TABLE tab_user ( tab_id varchar(50),  tab_title varchar(50),  user_login varchar(50),  sequence int,  display_type varchar(50),  locked int,  hide int);
DROP TABLE IF EXISTS tabs;
CREATE TABLE tabs ( tab_id varchar(100),  tab_title varchar(100),  user_login varchar(100),  sequence int,  display_type varchar(100));
DROP TABLE IF EXISTS user_css;
CREATE TABLE user_css ( user_login varchar(100),  css_name varchar(100));
DROP TABLE IF EXISTS user_module;
CREATE TABLE user_module ( tab_id varchar(100),  user_login varchar(100),  module_id varchar(100),  sequence int,  module_custom_title varchar(100),  column_number int);
DROP TABLE IF EXISTS user_module_template;
CREATE TABLE user_module_template ( tab_id varchar(100),  user_login varchar(100),  module_id varchar(100),  sequence int,  module_custom_title varchar(100),  column_number int);
DROP TABLE IF EXISTS user_timezone;
CREATE TABLE user_timezone ( user_id varchar(50),  time_zone_id varchar(100));
DROP TABLE IF EXISTS user_tracker;
CREATE TABLE user_tracker ( user_login varchar(50),  log_year int,  log_month int,  log_day int,  module_id varchar(50),  module_class varchar(100),  module_name varchar(100),  time12 varchar(50),  time24 varchar(50),  str_date varchar(50),  remote_add varchar(50),  log_date datetime);
DROP TABLE IF EXISTS users;
CREATE TABLE users ( user_login varchar(100),  user_password varchar(100),  user_name varchar(200),  user_role varchar(100),  user_login_alt varchar(50),  user_address varchar(255),  user_ip_address varchar(50),  date_registered datetime,  avatar varchar(50));
DROP TABLE IF EXISTS users_data;
CREATE TABLE users_data ( user_login varchar(100),  address varchar(255),  state varchar(50),  postcode varchar(10),  emp_address varchar(255),  emp_state varchar(50),  emp_postcode varchar(10),  email varchar(255),  hpno varchar(15),  telno varchar(15),  faxno varchar(15),  icno varchar(16),  age char,  gender char,  marital_status varchar(12),  date_of_birth date,  interest text,  academic varchar(255),  sector varchar(255),  current_job varchar(255));
DROP TABLE IF EXISTS web_log;
CREATE TABLE web_log ( ip_address varchar(50),  counter bigint,  last_log_date datetime,  first_log_date datetime);
DROP TABLE IF EXISTS web_log_init;
CREATE TABLE web_log_init ( init_date datetime);
DROP TABLE IF EXISTS web_logger;
CREATE TABLE web_logger ( remote_add varchar(50),  user_name varchar(50),  log_year int,  log_month int,  log_day int,  log_string varchar(255),  log_date datetime);
DROP TABLE IF EXISTS webmail_login;
CREATE TABLE webmail_login ( username varchar(50),  password varchar(100),  user_id varchar(50));
DROP TABLE IF EXISTS xml_module;
CREATE TABLE xml_module ( module_id varchar(100),  xml varchar(200),  xsl varchar(200));