alter table breakdown_marks add index(session_id, subject_id);
alter table course add index(course_id);
alter table course_enroll add index(course_id, member_id);
alter table course_portfolio_text add index(subject_id);
alter table course_sco add index(course_id, sco_id);
alter table course_structure add index(course_id, period_root_id, period_id, subject_id);
alter table course_url add index(subject_id);
alter table degree_scheme add index(scheme_id);
alter table degree_scheme_impl add index(scheme_id, session_id, program_code);
alter table enquiry add index(program_code, name);
alter table faculty add index(faculty_id, institution_id);
alter table faculty_subject add index(faculty_id, subject_id);
alter table fee_code add index(code);
alter table fee_structure_program add index(fee_id, period_id, fee_code, program_code, intake_session);
alter table forum add index(id, parent_id, category_id, member_id);
alter table forum_attachment add index(forum_id);
alter table gender_code add index(code);
alter table grading_scheme add index(scheme_id);
alter table grading_scheme_detail add index(scheme_id, grade_id);
alter table grading_scheme_impl add index(scheme_id, session_id, program_code);
alter table hd_categories add index(category_id);
alter table hd_escalation add index(enquiry_id, responsible_id);
alter table hd_group add index(group_id);
alter table hd_responsible_group add index(group_id, res_id);
alter table hd_responsibles add index(res_id);
alter table institution add index(institution_id);
alter table intake add index(intake_id);
alter table intake_batch add index(session_id, intake_session, period_root_id, period_id);
alter table learner_sco add index(sco_id, member_id);
alter table learning_centre add index(centre_id, institution_id);
alter table lesson add index(subject_id, lesson_id);
alter table lesson_content add index(lesson_id, content_id);
alter table letter_compose add index(letter_id);
alter table marital_code add index(code);
alter table marking_part add index(scheme_id, part_id);
alter table member add index(member_id);
alter table member_subject add index(member_id, subject_id, module_id);
alter table module add index(module_id);
alter table module_htmlcontainer add index(module_id);
alter table nationality_code add index(code);
alter table period add index(period_root_id, period_id, parent_id);
alter table period_root add index(period_root_id);
alter table planner_task add index(task_id, user_login, subject_id);
alter table planner_task_access add index(task_id, user_login);
alter table planner_task_invite add index(task_id, user_id, inviter_id);
alter table planner_task_post add index(task_id, user_id);
alter table program add index(course_id, period_root_id, program_code);
alter table program_intake add index(program_code, intake_session, period_root_id);
alter table program_track add index(program_code, track_id, period_root_id);
alter table quiz_assessment add index(assessment_id, subject_id);
alter table quiz_assessment_answer add index(user_id, assessment_id, question_id);
alter table quiz_assessment_attempt add index(user_id, assessment_id);
alter table quiz_assessment_questions add index(assessment_id, quiz_id);
alter table quiz_assessment_result add index(assessment_id, user_id);
alter table quiz_assessment_run add index(user_id, assessment_id, question_id);
alter table quiz_choice add index(choice_id, question_id);
alter table quiz_main add index(quiz_id, lesson_id, subject_id);
alter table quiz_question add index(question_id, quiz_id);
alter table race_code add index(code);
alter table religion_code add index(code);
alter table role_module add index(module_id);
alter table rss_module add index(module_id);
alter table sc_category add index(id);
alter table sc_content add index(user_login, itemId);
alter table sc_item add index(id, catId);
alter table sc_item_category add index(itemId, catId);
alter table sco add index(sco_id);
alter table sessions add index(session_id);
alter table sponsor add index(sponsor_id);
alter table state_code add index(code);
alter table student add index(id, name, icno, centre_id);
alter table student_billing add index(student_id, session_id, bill_no);
alter table student_billing_detail add index(student_id, bill_no, session_id, period_id, fee_id);
alter table student_biodata add index(student_id, icno);
alter table student_centre add index(student_id, centre_id, session_id);
alter table student_course add index(student_id, course_id, period_root_id, intake_session, program_code);
alter table student_deposit add index(student_id, icno, receipt_no, intake_session);
alter table student_marks add index(student_id, period_id, subject_id, part_id);
alter table student_marks_total add index(student_id, period_id, subject_id);
alter table student_receipt add index(student_id, receipt_no);
alter table student_receipt_detail add index(student_id, receipt_no, fee_id);
alter table student_sponsor add index(student_id, sponsor_id);
alter table student_status add index(student_id, session_id, batch_id);
alter table student_subject add index(student_id, period_root_id, period_id, subject_id, course_id, program_code);
alter table study_course add index(course_id, faculty_id);
alter table subject add index(subject_id, module_id);
alter table subject_program add index(subject_id, program_code);
alter table subject_reg_status add index(status_id);
alter table tab_template add index(tab_id);
alter table tabs add index(tab_id);
alter table teacher_comment add index(member_id, subject_id);
alter table transcript_display add index(student_id);
alter table tt_prepare_classroom add index(uid, subject_id, section_id, teacher_id, room_id);
alter table tt_schedule add index(uid, subject_id, section_id, teacher_id, room_id, day_id, slot_id);
alter table tt_section add index(uid, subject_id, section_id, student_id, session_id);
alter table user_css add index(user_login);
alter table user_module add index(tab_id, user_login, module_id);
alter table user_module_template add index(tab_id, user_login, module_id);
alter table user_tracker add index(user_login, module_id, log_date);
alter table users add index(user_login);
alter table xml_module add index(module_id);