DELETE FROM user_module;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_RegisterNewModule', 1, 'Register Module', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_RegisterUserModule', 4, 'Register User', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_portal_RenameGroupModule', 8, 'Rename Modules Group', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_util_RepositoryModule', 11, 'Repository', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_portal_PrepareUserModule', 9, 'Role Pages Template', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_RoleModule', 3, 'Roles', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_module_theme_PageStyleManagerModule', 10, 'Themes Manager', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_UpdateUserModule', 5, 'Update User', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_users_UserAdministratorModule', 6, 'List Users', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_RoleEditorModule', 7, 'User Modules Access Privilleges', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_portal_db_DbInfoModule', 12, 'Db Info', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191904545724', 'admin', 'lebah_app_ModuleEditor', 2, 'List Modules', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191921140711', 'anon', 'lebah_app_MessageModule', 2, 'Announcement', 1) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191921140711', 'anon', 'lebah_app_ForumModule', 3, 'Discussion Forum', 1) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191921140711', 'anon', 'lebah_app_shout_ShoutModule', 1, 'Shout Box', 0) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191921140725', 'admin', 'lebah_app_MessageModule', 2, 'Announcement', 1) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191921140725', 'admin', 'lebah_app_ForumModule', 3, 'Discussion Forum', 1) ;
INSERT INTO user_module (tab_id, user_login, module_id, sequence, module_custom_title, column_number)  VALUES ('1191921140725', 'admin', 'lebah_app_shout_ShoutModule', 1, 'Shout Box', 0) ;
